### ISSUE TITLE
no run

### ISSUE THREAD

**Issue by edwardes2201** [kahowang/Livox_Color_View_And_Mpping#1]
Hi, great job, congratulations. I have tried to run the code in fast mess but it does not give me any result. I follow the sequence of the publication and when executing the ...livox_color_mapping.launch the point cloud is not colored. Could you guide me or tell me how to configure it. thank you. greetings.

**Comment by kahowang** [comment]
Thank you very much for your attention. I was going to put the test dataset, but the dataset was lost. What kind of equipment do you have? If it is convenient, please give me the data set. I will try it. Thanks for your attention.

**Comment by edwardes2201** [comment]
HELLO, I STILL CANNOT MAKE IT WORK, I HAVE THE LIVOX MID 40, IMU witmotion wt901c, REALSENSE D345í, mini pc reatam 16 gb ram. I TRIED THE FASTLIO MODIFIED AND LIVOX ROS DRIVER MODIFIED FROM TOMATOO1107 BUT I CAN'T GET IT WORKING YET. WHAT REPOSITORY DID YOU USE OF FASTLIO AND DRIVER? I AM NEW TO THESE ISSUES, I WOULD GREATLY APPRECIATE YOUR HELP TO GET IT WORKING.

IN THE WINDOW WHERE FASTLIO IS RUNNING I GET:
process[laserMapping-1]: started with pid [8380]
process[rviz-2]: started with pid [8381]
Multi thread started 
p_pre->lidar_type 1
~~~~/home/edu/fastlio_mod/catkin_ws/src/FAST_LIO_Modified/ doesn't exist

WHERE THE LIVOX_ROS_DRIVER IS EXECUTED I GET:
Lidar start sample success
[ INFO] [1685124056.714942677]: ========================
[ INFO] [1685124056.715007774]: Init time stamp = 685253354880.000000
[ INFO] [1685124056.715041088]: ========================
[ INFO] [1685124056.715072569]: Support only one topic.
[ INFO] [1685124056.716320751]: livox/lidar publish use livox custom format, set ROS publisher queue size 256
[DEBUG] [1685124056.716392340]: Trying to publish message of type [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6] on a publisher with type [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6]
[ INFO] [1685124056.814946800]: ========================
[ INFO] [1685124056.815014191]: Init time stamp = 685300377310.000000
[ INFO] [1685124056.815043788]: ========================
[ INFO] [1685124056.861892612]: ========================
[ INFO] [1685124056.861956376]: Init time stamp = 685400414420.000000
[ INFO] [1685124056.861987747]: ========================
[ERROR] [1685124056.934630365]: Client [/laserMapping] wants topic /livox/lidar to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6]. Dropping connection.
[ INFO] [1685124056.962093347]: ========================
[ INFO] [1685124056.962159395]: Init time stamp = 685500454130.000000

THANKS FOR YOUR TIME.

**Comment by kahowang** [comment]
If possible, you can give me your dataset for advance testing.

**Comment by YYH2913** [comment]
这可能是因为livox_lidar.launch和livox_lidar_msg.launch存在不同的格式，你可以更换另一个launch试试

**Comment by kahowang** [comment]
Hello everyone, thank you for your attention. I recently updated the code to add a time soft synchronizer to the mapping code and provide data sets for simple validation, thank you~
