### ISSUE TITLE
question about mid360

### ISSUE THREAD

**Issue by EleSheep-moving** [kahowang/Livox_Color_View_And_Mpping#2]
我想请教一下大佬，请问您对将d435的颜色，赋色给类似mid360或者16线雷达的点云有什么见解吗？或者是全景相机和16线雷达，毕竟两者的FOV出入非常之大

**Comment by Lavinci** [comment]
![image](https://github.com/kahowang/Livox_Color_View_And_Mpping/assets/28396966/166ddcae-c4a4-4708-993b-2019d1ed8290)
实测可以用的，建图也是没有问题的
![QQ截图20240401160131](https://github.com/kahowang/Livox_Color_View_And_Mpping/assets/28396966/d425293b-d73d-45aa-b745-4e2f231eb01c)

**Comment by kahowang** [comment]
> ![image](https://private-user-images.githubusercontent.com/28396966/318382992-166ddcae-c4a4-4708-993b-2019d1ed8290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjcxNjcsIm5iZiI6MTcxMTk2Njg2NywicGF0aCI6Ii8yODM5Njk2Ni8zMTgzODI5OTItMTY2ZGRjYWUtYzRhNC00NzA4LTk5M2ItMjAxOWQxZWQ4MjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwMjEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxN2EzMWIzOGZkMWQyNTJhYzAyNDQyNzQzMTBiMTlhOGQxZDM3NzIwYWJhOTJlY2RkMmVjNDgzYjEyZWNhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xsKfY_z8ZKrE9nRxNnm6SDB-MQxNnmJSEPP7TsjSSNo) 实测可以用的，建图也是没有问题的 ![QQ截图20240401160131](https://private-user-images.githubusercontent.com/28396966/318383149-d425293b-d73d-45aa-b745-4e2f231eb01c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjcxNjcsIm5iZiI6MTcxMTk2Njg2NywicGF0aCI6Ii8yODM5Njk2Ni8zMTgzODMxNDktZDQyNTI5M2ItZDczZC00NWFhLWI3NDUtNGUyZjIzMWViMDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwMjEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZGM5MzkyYzljZWJmZmNhMGU5ZDg1OGE1NTdmYjZlM2I4NzhkNWU5YjZkZDE5ODEyNjk2ZDVkMmJkMDM1OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f6JcTKvWSOCTK6MgDjV6mRQf9eQTSXFoIONiDshIfl8)

Nice job. It is so cool! Thank you for your great help~

**Comment by silenceghost** [comment]
> ![image](https://private-user-images.githubusercontent.com/28396966/318382992-166ddcae-c4a4-4708-993b-2019d1ed8290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzQ1MDgsIm5iZiI6MTczMzI3NDIwOCwicGF0aCI6Ii8yODM5Njk2Ni8zMTgzODI5OTItMTY2ZGRjYWUtYzRhNC00NzA4LTk5M2ItMjAxOWQxZWQ4MjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAxMDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNjAzZjIyMjI1NGRjMTJjNjI0MGI0MmQxNDI4OWNlMTE3ZDEyZGE4ZmQwOWM1NTBiZTBlZDdlOGE5YjA5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kqy_AfMuF8mmd3GiHE-W6EuYAuhiEb78D6_fp-WyJWc) 实测可以用的，建图也是没有问题的 ![QQ截图20240401160131](https://private-user-images.githubusercontent.com/28396966/318383149-d425293b-d73d-45aa-b745-4e2f231eb01c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzQ1MDgsIm5iZiI6MTczMzI3NDIwOCwicGF0aCI6Ii8yODM5Njk2Ni8zMTgzODMxNDktZDQyNTI5M2ItZDczZC00NWFhLWI3NDUtNGUyZjIzMWViMDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAxMDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZjhkZTBlMzg4NTNkNTMyZWRjODBmMGRhOTg1ZWU2MDBiOTU3MGJlZjliODJlOWEzNGFhMjBlOTE4MTUzZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8e6X6RP3d2uHLjakN-MkFkUzCe_lZnPI85ADGUoXpr4)

Hello, may I ask if livox_camera_calib is also used for calibrating the camera and the camera? During the mid360 calibration process, does it need to cover the LiDAR scanning part other than the camera direction? Thank you
