### ISSUE TITLE
question about running

### ISSUE THREAD

**Issue by jllk47** [kahowang/Livox_Color_View_And_Mpping#3]
您好作者，我想通过mid40+realsense自带的imu进行了fastlio的彩色建图，然而在您的仓库中我没有找到roslaunch fast_lio mapping_mid70_manual.launch这个launch文件，并且还有问题是在建图过程中播放bag文件需要录制什么话题呢？如果您能回答我将万分感激

![1702520179679](https://github.com/kahowang/Livox_Color_View_And_Mpping/assets/129836501/c259fdea-82f5-4d28-bb25-10922d5045ea)

**Comment by LiSi0205** [comment]
您好，我也是编译好了文件之后发现并没有roslaunch fast_lio mapping_mid70_manual.launch这个launch文件，您解决了吗？
