### ISSUE TITLE
SAVE MAP

### ISSUE THREAD

**Issue by edwardes2201** [kahowang/Livox_Color_View_And_Mpping#5]
HELLO FRIEND, I AM TRYING YOUR CODE, BUT I HAVE A PROBLEM, I CAN'T SAVE THE MAP. HOW DO I SAVE. GREETINGS.

common:
  lidar_topic:  "/cloud_registered"                  # From FASTLIO2
  lidar_color_topic:  "/livox/color_lidar" #"/color_lidar"      # Pub color pointcloud
  odom_topic:  "/Odometry"                             # From FASTLIO2
  camera_topic:  "/camera/color/image_raw"
  frame_id: "camera_init"                                   # From FASTLIO2 's  frame_link

mapping:
  extrinsicT: [ -0.00387009, -0.999881, -0.0149254, 0.0801424,
                 0.0207012, 0.0148422, -0.999676, -0.117954,
                 0.999778, -0.0041778, 0.0206413, -0.0199456,
                 0.0, 0.0, 0.0, 1]        #  lidar2camera 外参  From livox_camera_calib

  intrisicT: [ 911.1104736328125, 0.0, 641.907470703125, 
                    0.0, 910.8844604492188, 362.8921813964844, 
                     0.0, 0.0, 1.0]           # camera 内参

  ditortion: [0.0, 0.0, 0.0, 0.0, 0.0]      # camera 畸变系数

savepcd:
  savePCDDirectory: "/home/edu/livox_color/PCD/"

**Comment by kahowang** [comment]
Hello thank you for your following. I think you can try `source devel/setup.bash  &  rosservice call /save_map "{}"` in your ROS workspace ~

**Comment by edwardes2201** [comment]
HELLO FRIEND, THANK YOU FOR YOUR RESPONSE, I AM USING THE FOLLOWING COMMAND COMBINATION TO EXECUTE YOUR CODE, THE COLORED CLOUD APPEARS NORMAL IN THE RVIZ BUT IT IS NOT SAVED ANYWHERE. I PUT WHAT YOU TOLD ME, I DON'T KNOW IF I DID IT WELL. GREETINGS

#!/bin/bash
gnome-terminal --tab --title="d435i" -- bash -c "cd camera_calib/d435i/catkin_ws; source devel/setup.bash; roslaunch realsense2_camera rs_camera.launch"
sleep 3
gnome-terminal --tab --title="Wit" -- bash -c "cd fastlio_lc/imu_ws; source devel/setup.bash; echo | sudo -S chmod 777 /dev/ttyUSB0; roslaunch wit_node wit.launch"
sleep 3
gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd fastlio_lc/catkin_ws; source devel/setup.bash; roslaunch fast_lio mapping_avia.launch"
sleep 3
gnome-terminal --tab --title="Livoxros" -- bash -c "cd fast_lio/ws_livox_mod; source devel/setup.bash; roslaunch livox_ros_driver livox_lidar_msg.launch"
sleep 3
gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd livox_color/catkin_ws; rosservice call /save_map "{}""
sleep 3
gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd livox_color/catkin_ws; source devel/setup.bash ; roslaunch livox_color livox_color_mapping.launch"

**Comment by kahowang** [comment]
Hello thank you for your following. Could you corect the PCD save path in` livox_color/config/livox_color_mapping.yaml`   

> savepcd:
>   savePCDDirectory: "/livox_color_ws/src/livox_color/PCD/"

**Comment by edwardes2201** [comment]
HELLO FRIEND, FINALLY WORKING NOW I CAN SAVE THE MAP, HOWEVER MY DATA OBTAINED IS NOT AS GOOD AS YOUR IMAGES. I THINK IT MAY BE BECAUSE OF THE EXTERNAL IMU WITH THE LIVOX MID 40 THEY ARE NOT CORRECTLY SYNCHRONIZED. ON THE OTHER HAND I AM TRYING TO MERGE YOUR CODE SO THAT IT WORKS WITH THE livox_scanner BUT THE COLORED CLOUD IS DISTORTED WHEN ROTATING THE LIDAR IN ITS Z AXIS. ANY SUGGESTIONS TO BE ABLE TO MATCH THE COLORING CORRECTLY.

GREETINGS

![WhatsApp Image 2024-02-29 at 1 40 25 PM](https://github.com/kahowang/Livox_Color_View_And_Mpping/assets/55101190/2e817e54-199a-4bc6-9f70-3cf4c5808e21)

**Comment by lwdone** [comment]
> HELLO FRIEND, FINALLY WORKING NOW I CAN SAVE THE MAP, HOWEVER MY DATA OBTAINED IS NOT AS GOOD AS YOUR IMAGES. I THINK IT MAY BE BECAUSE OF THE EXTERNAL IMU WITH THE LIVOX MID 40 THEY ARE NOT CORRECTLY SYNCHRONIZED. ON THE OTHER HAND I AM TRYING TO MERGE YOUR CODE SO THAT IT WORKS WITH THE livox_scanner BUT THE COLORED CLOUD IS DISTORTED WHEN ROTATING THE LIDAR IN ITS Z AXIS. ANY SUGGESTIONS TO BE ABLE TO MATCH THE COLORING CORRECTLY.
> 
> GREETINGS
> 
> ![WhatsApp Image 2024-02-29 at 1 40 25 PM](https://private-user-images.githubusercontent.com/55101190/309037600-2e817e54-199a-4bc6-9f70-3cf4c5808e21.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NzI5OTYsIm5iZiI6MTcwOTQ3MjY5NiwicGF0aCI6Ii81NTEwMTE5MC8zMDkwMzc2MDAtMmU4MTdlNTQtMTk5YS00YmM2LTlmNzAtM2NmNGM1ODA4ZTIxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxMzMxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjFlNWUyMWVhOGRhZDljM2M1Y2U4ZDY4YWU2MWE0NjdjNGFmZDY2NDI0Nzk2MjA5NjM5YTk3OTkzNDc2NmVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P5ZxNUYhpDjWUmVZNv0XH3MhsJYzCh9zC339q-3UY8g)

Hello, glad you saved the map in color. I have some questions to ask you. When I run the code, I cannot print out the color map. First of all, if the radar releases cloudpoint2 type point cloud, fastlio2 cannot run. If the radar releases the msg format point cloud format, and then runs livox_color_mapping.launch, there will be only point clouds and no colors. How to solve this?
The first picture shows Radar releasing Dianyun in cloudpiont2 format to run fastlio2, and Radar reports an error.
The second picture is after the radar releases the point cloud in msg format and runs fastlio2 and livox_color_mapping.launch, there is no color.
![Uploading 2024-03-03 21-36-15 的屏幕截图.png…]()

greeting

**Comment by lwdone** [comment]
![2024-03-03 21-38-06 的屏幕截图](https://github.com/kahowang/Livox_Color_View_And_Mpping/assets/152387940/73f8df91-b4ce-4a4f-8294-0aeec26c54ab)

**Comment by lwdone** [comment]
![Uploading 2024-03-03 21-36-15 的屏幕截图.png…]()

**Comment by lwdone** [comment]
![Uploading 2024-03-03 21-36-15 的屏幕截图.png…]()

**Comment by lwdone** [comment]
![2024-03-03 21-36-15 的屏幕截图](https://github.com/kahowang/Livox_Color_View_And_Mpping/assets/152387940/2150d42e-613c-426b-b7ec-df986f016f68)


> ![2024-03-03 21-38-06 的屏幕截图](https://private-user-images.githubusercontent.com/152387940/309553969-73f8df91-b4ce-4a4f-8294-0aeec26c54ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NzM1NTQsIm5iZiI6MTcwOTQ3MzI1NCwicGF0aCI6Ii8xNTIzODc5NDAvMzA5NTUzOTY5LTczZjhkZjkxLWI0Y2UtNGE0Zi04Mjk0LTBhZWVjMjZjNTRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxMzQwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzE2N2NiNGQ0NjU5NWVkMmZjOGRmNGU2YjViMDM0OThkZDM0MzNiZmY1NGNjMWQwOTk0YjIyODA2OWZkZGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tHU8NaBlGV3MqN_CIGUNvjWfRs8pSy6ySvDszw9OYz4)

**Comment by edwardes2201** [comment]
HELLO FRIEND, THIS SEQUENCE FOLLOWED TO EXECUTE THE CODES ONE AFTER ANOTHER. IN MY CASE I USE THE MID40, WITMOTION IMU, AND REALSENSE D345i, AND I MODIFIED THE LIVOX_COLOR CONFIGURATION .YAML FILE. MAYBE YOU NEED TO EXECUTE ONE MORE SEQUENCE. GREETINGS.

#!/bin/bash
gnome-terminal --tab --title="d435i" -- bash -c "cd camera_calib/d435i/catkin_ws; source devel/setup.bash; roslaunch realsense2_camera rs_camera.launch"
sleep 3
gnome-terminal --tab --title="Wit" -- bash -c "cd fastlio_lc/imu_ws; source devel/setup.bash; echo | sudo -S chmod 777 /dev/ttyUSB0; roslaunch wit_node wit.launch"
sleep 3
gnome- terminal --tab --title="Lidar_mapping" -- bash -c "cd fastlio_lc/catkin_ws; fuente devel/setup.bash; roslaunch fast_lio mapeo_avia.launch"
dormir 3
gnome-terminal --tab --title="Livoxros" -- bash -c "cd fast_lio/ws_livox_mod; source devel/setup.bash; roslaunch livox_ros_driver livox_lidar_msg.launch"
sleep 3
gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd livox_color/catkin_ws; source devel/setup.bash ; roslaunch livox_color livox_color_mapping.launch"
sleep 3
gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd livox_color/catkin_ws; rosservice call /save_map "{}""

**Comment by lwdone** [comment]
> HELLO FRIEND, THIS SEQUENCE FOLLOWED TO EXECUTE THE CODES ONE AFTER ANOTHER. IN MY CASE I USE THE MID40, WITMOTION IMU, AND REALSENSE D345i, AND I MODIFIED THE LIVOX_COLOR CONFIGURATION .YAML FILE. MAYBE YOU NEED TO EXECUTE ONE MORE SEQUENCE. GREETINGS.
> 
> #!/bin/bash gnome-terminal --tab --title="d435i" -- bash -c "cd camera_calib/d435i/catkin_ws; source devel/setup.bash; roslaunch realsense2_camera rs_camera.launch" sleep 3 gnome-terminal --tab --title="Wit" -- bash -c "cd fastlio_lc/imu_ws; source devel/setup.bash; echo | sudo -S chmod 777 /dev/ttyUSB0; roslaunch wit_node wit.launch" sleep 3 gnome- terminal --tab --title="Lidar_mapping" -- bash -c "cd fastlio_lc/catkin_ws; fuente devel/setup.bash; roslaunch fast_lio mapeo_avia.launch" dormir 3 gnome-terminal --tab --title="Livoxros" -- bash -c "cd fast_lio/ws_livox_mod; source devel/setup.bash; roslaunch livox_ros_driver livox_lidar_msg.launch" sleep 3 gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd livox_color/catkin_ws; source devel/setup.bash ; roslaunch livox_color livox_color_mapping.launch" sleep 3 gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd livox_color/catkin_ws; rosservice call /save_map "{}""


Hello, my equipment is mid70, wit motion im, astro pro.
I run the sequence
 1. Start the camera node
cd tools/usb_cam_ws/
 source devel/setup.bash
 roslaunch usb_cam usb_cam.launch
2. Start the imu node
source devel/setup.bash
sudo chmod 777 /dev/ttyUSB0
 roslaunch wit_node wit.launch
3. Start the lidar node
source devel/setup.bash
roslaunch livox_ros_driver livox_lidar_msg.launch
4. Start fastlio
source devel/setup.bash
 roslaunch fast_lio mapping_avia.launch
Finally start livox-color
source devel/setup.bash
roslaunch livox_color livox_color_mapping.launch
But there is no rgb color. How did you modify your livox_lidar.yaml file? Have you modified the camera parameters?
I can run source devel/setup.bash
roslaunch livox_color livox_color_view.launch
The color can be seen with this, but roslaunch livox_color livox_color_mapping.launch cannot

**Comment by lwdone** [comment]
> HELLO FRIEND, THIS SEQUENCE FOLLOWED TO EXECUTE THE CODES ONE AFTER ANOTHER. IN MY CASE I USE THE MID40, WITMOTION IMU, AND REALSENSE D345i, AND I MODIFIED THE LIVOX_COLOR CONFIGURATION .YAML FILE. MAYBE YOU NEED TO EXECUTE ONE MORE SEQUENCE. GREETINGS.
> 
> #!/bin/bash gnome-terminal --tab --title="d435i" -- bash -c "cd camera_calib/d435i/catkin_ws; source devel/setup.bash; roslaunch realsense2_camera rs_camera.launch" sleep 3 gnome-terminal --tab --title="Wit" -- bash -c "cd fastlio_lc/imu_ws; source devel/setup.bash; echo | sudo -S chmod 777 /dev/ttyUSB0; roslaunch wit_node wit.launch" sleep 3 gnome- terminal --tab --title="Lidar_mapping" -- bash -c "cd fastlio_lc/catkin_ws; fuente devel/setup.bash; roslaunch fast_lio mapeo_avia.launch" dormir 3 gnome-terminal --tab --title="Livoxros" -- bash -c "cd fast_lio/ws_livox_mod; source devel/setup.bash; roslaunch livox_ros_driver livox_lidar_msg.launch" sleep 3 gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd livox_color/catkin_ws; source devel/setup.bash ; roslaunch livox_color livox_color_mapping.launch" sleep 3 gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd livox_color/catkin_ws; rosservice call /save_map "{}""

Hello, my equipment is mid70, wit motion im, astro pro.
I run the sequence
 1. Start the camera node
cd tools/usb_cam_ws/
 source devel/setup.bash
 roslaunch usb_cam usb_cam.launch
2. Start the imu node
source devel/setup.bash
sudo chmod 777 /dev/ttyUSB0
 roslaunch wit_node wit.launch
3. Start the lidar node
source devel/setup.bash
roslaunch livox_ros_driver livox_lidar_msg.launch
4. Start fastlio
source devel/setup.bash
 roslaunch fast_lio mapping_avia.launch
5.Finally start livox-color
source devel/setup.bash
roslaunch livox_color livox_color_mapping.launch




But there is no rgb color. How did you modify your livox_lidar.yaml file? Have you modified the camera parameters?
I can run source devel/setup.bash
roslaunch livox_color livox_color_view.launch
The color can be seen with this, but roslaunch livox_color livox_color_mapping.launch cannot

**Comment by lwdone** [comment]
> HELLO FRIEND, THIS SEQUENCE FOLLOWED TO EXECUTE THE CODES ONE AFTER ANOTHER. IN MY CASE I USE THE MID40, WITMOTION IMU, AND REALSENSE D345i, AND I MODIFIED THE LIVOX_COLOR CONFIGURATION .YAML FILE. MAYBE YOU NEED TO EXECUTE ONE MORE SEQUENCE. GREETINGS.
> 
> #!/bin/bash gnome-terminal --tab --title="d435i" -- bash -c "cd camera_calib/d435i/catkin_ws; source devel/setup.bash; roslaunch realsense2_camera rs_camera.launch" sleep 3 gnome-terminal --tab --title="Wit" -- bash -c "cd fastlio_lc/imu_ws; source devel/setup.bash; echo | sudo -S chmod 777 /dev/ttyUSB0; roslaunch wit_node wit.launch" sleep 3 gnome- terminal --tab --title="Lidar_mapping" -- bash -c "cd fastlio_lc/catkin_ws; fuente devel/setup.bash; roslaunch fast_lio mapeo_avia.launch" dormir 3 gnome-terminal --tab --title="Livoxros" -- bash -c "cd fast_lio/ws_livox_mod; source devel/setup.bash; roslaunch livox_ros_driver livox_lidar_msg.launch" sleep 3 gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd livox_color/catkin_ws; source devel/setup.bash ; roslaunch livox_color livox_color_mapping.launch" sleep 3 gnome-terminal --tab --title="Lidar_mapping" -- bash -c "cd livox_color/catkin_ws; rosservice call /save_map "{}""


This is my configuration file.
common:
  lidar_topic:  "/cloud_registered"                  # From FASTLIO2
  lidar_color_topic:  "/livox/color_lidar" #"/color_lidar"      # Pub color pointcloud
  odom_topic:  "/Odometry"                             # From FASTLIO2
  camera_topic:  "/camera/color/image_raw"
  frame_id: "camera_init"                                   # From FASTLIO2 's  frame_link

mapping:
  extrinsicT: [0.0133378,-0.999702,-0.0204405,1.17467
-0.0701828,0.0194559,-0.997344,4.19568
0.997445,0.014737,-0.0699023,-3.79472
0,0,0,1]        #  lidar2camera 外参  From livox_camera_calib

  intrisicT: [ 645.39697265625 , 0, 627.2928466796875,
               0, 644.8126220703125, 356.3106689453125,
               0, 0, 1]           # camera 内参

  ditortion: [-0.055537205189466476 , 0.06588292121887207 , -0.0013024559011682868  ,-0.0010083256056532264,  -0.02116576768457889]      # camera 畸变系数

savepcd:
  savePCDDirectory: "/livox_color_ka/src/PCD"

**Comment by kahowang** [comment]
> HELLO FRIEND, FINALLY WORKING NOW I CAN SAVE THE MAP, HOWEVER MY DATA OBTAINED IS NOT AS GOOD AS YOUR IMAGES. I THINK IT MAY BE BECAUSE OF THE EXTERNAL IMU WITH THE LIVOX MID 40 THEY ARE NOT CORRECTLY SYNCHRONIZED. ON THE OTHER HAND I AM TRYING TO MERGE YOUR CODE SO THAT IT WORKS WITH THE livox_scanner BUT THE COLORED CLOUD IS DISTORTED WHEN ROTATING THE LIDAR IN ITS Z AXIS. ANY SUGGESTIONS TO BE ABLE TO MATCH THE COLORING CORRECTLY.
> 
> GREETINGS
> 
> ![WhatsApp Image 2024-02-29 at 1 40 25 PM](https://private-user-images.githubusercontent.com/55101190/309037600-2e817e54-199a-4bc6-9f70-3cf4c5808e21.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTk5MzIsIm5iZiI6MTcwOTUxOTYzMiwicGF0aCI6Ii81NTEwMTE5MC8zMDkwMzc2MDAtMmU4MTdlNTQtMTk5YS00YmM2LTlmNzAtM2NmNGM1ODA4ZTIxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwMjMzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjQ0YzI4NjFkMTVjYjFiMzdmM2Y1ODVhYTY4ZTdhNjBhYjJhMTY1ZmUxNDIzNTZjMjY0MjI1ZmFhNzMzOGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OXSa42ZIs4-3QkJRSl4tDAmqyafKIiGVsX4jd58aAeE)

Hello,  friend
Thank you for your following. Here is my suggestions:
1. You can confirm the extrinsic between your LiDAR and camear. I think you can use livox-color-view to check out your extrinsic result in some special environmenet.
2. I notice that " AM TRYING TO MERGE YOUR CODE SO THAT IT WORKS WITH THE livox_scanner BUT THE COLORED CLOUD IS DISTORTED WHEN ROTATING THE LIDAR IN ITS Z AXIS" , I think the problem may be the error of your SLAM method? 

Lookin for your reply. 
Kaho

**Comment by edwardes2201** [comment]
HELLO FRIEND, THANKS FOR RESPONDING. VERIFY THE CALIBRATION AND THE PARAMETERS ARE CORRECT. THE PROBLEM IS WHEN THE LIDAR ROTATES THEY CANNOT SYNCHRONIZE CORRECTLY. THE LIVOX_SCANN DOES NOT USE ODOMETRY, IT GENERATES THE POINT CLOUD WITH THE ENGINE ANGLE DATA AND IN PRACTICE IT IS ACCURATE.

![WhatsApp Image 2024-03-07 at 11 42 23 PM](https://github.com/kahowang/Livox_Color_View_And_Mpping/assets/55101190/c5482e01-8434-4952-8c6a-403859216a5e)

**Comment by kahowang** [comment]
> HELLO FRIEND, THANKS FOR RESPONDING. VERIFY THE CALIBRATION AND THE PARAMETERS ARE CORRECT. THE PROBLEM IS WHEN THE LIDAR ROTATES THEY CANNOT SYNCHRONIZE CORRECTLY. THE LIVOX_SCANN DOES NOT USE ODOMETRY, IT GENERATES THE POINT CLOUD WITH THE ENGINE ANGLE DATA AND IN PRACTICE IT IS ACCURATE.
> 
> ![WhatsApp Image 2024-03-07 at 11 42 23 PM](https://private-user-images.githubusercontent.com/55101190/311118686-c5482e01-8434-4952-8c6a-403859216a5e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NzgxMjIsIm5iZiI6MTcwOTg3NzgyMiwicGF0aCI6Ii81NTEwMTE5MC8zMTExMTg2ODYtYzU0ODJlMDEtODQzNC00OTUyLThjNmEtNDAzODU5MjE2YTVlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQwNjAzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWNjNTIwOGU3NmU2YTg2ZjcxNmQ3YTAyZWQ0MzU3OGRlNGRhMmI3NmY3MzRmZjUyYWMwYzlkZTY0ODVjNTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1te4bRO7lJX-WSL-dYsrQiTBVbelABVwG_GP4keEoKs)

Nice job, thank you for your following again.
