### ISSUE TITLE
有关保存彩色地图的问题

### ISSUE THREAD

**Issue by LiSi0205** [kahowang/Livox_Color_View_And_Mpping#6]
作者您好，非常敬佩您的工作，对您发布的兴趣十分感兴趣。但是我在学习的时候，发现了一些问题。
这里说到已经有了fastlio2的相关yaml文件，但是我并没有找到。是否是代码已经更新了？
在这里雷达使用的是livox_lidar.launch 。运行fastlio2使用的是livox_lidar_msg.launch，这里应该使用哪一种呢？我不知道是否是缺少上述文件的问题，我运行之后没有反应。
![Uploading Snipaste_2024-02-28_16-01-48.png…]()

**Comment by kahowang** [comment]
需要提前运行一次fastlio的代码
