### ISSUE TITLE
fast lio需要自定义的msg格式 ，本项目需要cloudpoint2格式？请问需要怎么同时得到这两种点云，谢谢

### ISSUE THREAD

**Issue by doche** [kahowang/Livox_Color_View_And_Mpping#7]
fast lio需要自定义的msg格式 ，本项目需要cloudpoint2格式？请问需要怎么同时得到这两种点云

**Comment by LiSi0205** [comment]
你好，你解决这个问题了吗？我首先运行cloudpoint2格式的话，就运行不了faslio2，后面运行roslaunch livox_color livox_color_mapping.launch 也是不显示点云的。
如果雷达发布msg格式的话。运行fastlio2，然后运行roslaunch livox_color livox_color_mapping.launch，只有点云，没有颜色。不知道该怎么处理。
但是roslaunch livox_color livox_color_view.launch这个是可以运行的。
可以交流一下吗？

**Comment by kahowang** [comment]
> fast lio需要自定义的msg格式 ，本项目需要cloudpoint2格式？请问需要怎么同时得到这两种点云

非常感谢您的关注，
1.本工程是基于FASTLIO2发布的点云工程，FASTLIO2运行时，发布的点云是pointcloud2类型，而livox-color 接受的点云类型是pointcloud2类型。所以，运行顺序应该是，先运行FASTLIO2(接入点云可能是livox-msg或者pointcloud2)，然后livox-color订阅FASTLIO2输出的点云。
2.同时本工程提供已录制好的FASTLIO2输出点云数据集，供直使用了livox-color   [https://github.com/kahowang/Livox_Color_View_And_Mpping/tree/main?tab=readme-ov-file#quick-test-by-dataset](url)
再次感谢关注~

**Comment by lwdone** [comment]
> > fast lio需要自定义的msg格式 ，本项目需要cloudpoint2格式？请问需要怎么同时得到这两种点云
> 
> 非常感谢您的关注， 1.本工程是基于FASTLIO2发布的点云工程，FASTLIO2运行时，发布的点云是pointcloud2类型，而livox-color 接受的点云类型是pointcloud2类型。所以，运行顺序应该是，先运行FASTLIO2(接入点云可能是livox-msg或者pointcloud2)，然后livox-color订阅FASTLIO2输出的点云。 2.同时本工程提供已录制好的FASTLIO2输出点云数据集，供直使用了livox-color [https://github.com/kahowang/Livox_Color_View_And_Mpping/tree/main?tab=readme-ov-file#quick-test-by-dataset](url) 再次感谢关注~

 是的，我运行了fastlio2，雷达发布的是msg格式，然后运行livox_color rviz中只有点云，没有rgb，这个是那里出了问题呢。我可以运行livox_color_view.launch，这里面有rgb，但是运行livox_color_mapping.launch没有rgb

**Comment by kahowang** [comment]
> > > fast lio需要自定义的msg格式 ，本项目需要cloudpoint2格式？请问需要怎么同时得到这两种点云
> > 
> > 
> > 非常感谢您的关注， 1.本工程是基于FASTLIO2发布的点云工程，FASTLIO2运行时，发布的点云是pointcloud2类型，而livox-color 接受的点云类型是pointcloud2类型。所以，运行顺序应该是，先运行FASTLIO2(接入点云可能是livox-msg或者pointcloud2)，然后livox-color订阅FASTLIO2输出的点云。 2.同时本工程提供已录制好的FASTLIO2输出点云数据集，供直使用了livox-color [https://github.com/kahowang/Livox_Color_View_And_Mpping/tree/main?tab=readme-ov-file#quick-test-by-dataset](url) 再次感谢关注~
> 
> 是的，我运行了fastlio2，雷达发布的是msg格式，然后运行livox_color rviz中只有点云，没有rgb，这个是那里出了问题呢。我可以运行livox_color_view.launch，这里面有rgb，但是运行livox_color_mapping.launch没有rgb


livox_color_view有RGB信息，livox_color_mapping没有RGB信息，可能是两个原因
1.Rviz显示原因，没有调整Rviz的点云RGB显示
2.livox_color_mapping 传感器时间对齐有一定的错误

**Comment by lwdone** [comment]
rviz这里/livox/color_lidar  这里的position transformer 和 color transformer 里面是空的，没有信息。 
我录制了rosbag包，传感器的时间都一样。我根据csdn对livox_ros_driver进行了改写，使其时间戳一致。但是我不知道是什么问题了，
![2024-03-04 11-50-56 的屏幕截图](https://github.com/kahowang/Livox_Color_View_And_Mpping/assets/152387940/65bfe665-e234-4f18-b25a-1d5042eb5a17)

**Comment by lwdone** [comment]
![2024-03-04 15-02-39 的屏幕截图](https://github.com/kahowang/Livox_Color_View_And_Mpping/assets/152387940/3ea76e1f-0f91-4d09-aa56-40f74f88fff0)
我终于出来rgb了。但是左侧这边的参数可以在rviz直接改吗？我改了之后又变成原来的数值了，必须通过改文件去改吗？

**Comment by kahowang** [comment]
你好，感谢您的关注。可以通过Rviz 右上角那行保存Rviz设置
