### ISSUE TITLE
有关使用第二套激光雷达扫描建图的问题

### ISSUE THREAD

**Issue by RemoteDream2000** [kahowang/Livox_Color_View_And_Mpping#8]
作者您好，感谢您的工作使我受益匪浅～ 我目前在尝试使用Livox Mid-70与IMU模块运行FAST_LIO输出里程计/Odometry，同时使用Velodyne Puck (VLP-16) 扫描另一方向的点云，录制rosbag，在您代码的基础上将点云topic名称修改为对应的/velodyne_points和/velodyne_color，但roslaunch运行时点云无法随里程计形成点云地图；请问您有没有类似情景的经验指导？若能收到回复，不胜感激！

**Comment by kahowang** [comment]
您好，感谢您的关注，可以先确认一下，接入里程计的话题是否正确，谢谢
kaho

**Comment by RemoteDream2000** [comment]
是的，我这边生成里程计的方案和您的方案相同，使用FAST_LIO2，所以odom_topic还是使用/Odometry

**Comment by kahowang** [comment]
> 是的，我这边生成里程计的方案和您的方案相同，使用FAST_LIO2，所以odom_topic还是使用/Odometry

可能是代码里，原来是根据livox去适配的，livox前向fov是70度，你换成vlp-16，应该需要调整一下代码对应部分。希望对你有帮助，谢谢~

**Comment by RemoteDream2000** [comment]
您好，我这边调试了一下，问题应该不是出在FOV上，而是mid-70的/camera_init坐标系和vlp-16的/velodyne坐标系没有建立有效的tf2动态坐标变换连接，目前的问题已经解决，非常感谢您的回复～
